name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Install dependencies, Analyze and Test
      run: |
        for dir in */; do
          if [ -f "$dir/pubspec.yaml" ]; then
            echo "Building $dir"
            cd "$dir"
            flutter pub get
            flutter analyze || echo "Ignoring lint errors for now"
            if [ -d "test" ] && ls "test"/*_test.dart 1> /dev/null 2>&1; then
              flutter test || echo "Ignoring test failures for now"
            fi
            cd ..
          fi
        done
